
spring:
  datasource:
    url: "jdbc:h2:mem:test;MODE=MYSQL"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      minimum-idle: 1
      pool-name: H2_DB
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
